### ISSUE TITLE
listFiles does not like filenames with spaces

### ISSUE THREAD

**Issue by raymondben** [INWTlab/rsync#9]
https://github.com/INWTlab/rsync/blob/master/R/listFiles.R#L21 will split file/directory names that have spaces in them

**Comment by wahani** [comment]
@raymondben Thanks for taking the time to report this issue!

I have prepared a fix which you may try after installing the patched version with:

```r
remotes::install_github("INWTLab/rsync", ref = "feature/9_listFiles-does-not-like-filenames-with-spaces")
```

Can you please also provide an example of your use case, so that I can make sure it is now covered by the test cases?

**Comment by raymondben** [comment]
@wahani thanks, see comments in https://github.com/INWTlab/rsync/pull/11

**Comment by wahani** [comment]
@raymondben thanks again. The patch is in master now. You can receive updates using:

```
options(repos = c(getOption("repos"), INWTLab = "https://inwtlab.github.io/drat/"))
install.packages("rsync")
```
